In [1]:
import numpy as np

In [2]:
N=int(input("Enter arrays length: "))

Enter arrays length: 100


In [3]:
arr1 = np.arange(0, N, 1)
arr2 = np.arange(0, 1, 1/N)

In [4]:
res_arr = np.zeros(N, dtype=float)
for i in range(0, N):
    res_arr[i] = arr1[i] + arr2[i]
res_arr

array([ 0.  ,  1.01,  2.02,  3.03,  4.04,  5.05,  6.06,  7.07,  8.08,
        9.09, 10.1 , 11.11, 12.12, 13.13, 14.14, 15.15, 16.16, 17.17,
       18.18, 19.19, 20.2 , 21.21, 22.22, 23.23, 24.24, 25.25, 26.26,
       27.27, 28.28, 29.29, 30.3 , 31.31, 32.32, 33.33, 34.34, 35.35,
       36.36, 37.37, 38.38, 39.39, 40.4 , 41.41, 42.42, 43.43, 44.44,
       45.45, 46.46, 47.47, 48.48, 49.49, 50.5 , 51.51, 52.52, 53.53,
       54.54, 55.55, 56.56, 57.57, 58.58, 59.59, 60.6 , 61.61, 62.62,
       63.63, 64.64, 65.65, 66.66, 67.67, 68.68, 69.69, 70.7 , 71.71,
       72.72, 73.73, 74.74, 75.75, 76.76, 77.77, 78.78, 79.79, 80.8 ,
       81.81, 82.82, 83.83, 84.84, 85.85, 86.86, 87.87, 88.88, 89.89,
       90.9 , 91.91, 92.92, 93.93, 94.94, 95.95, 96.96, 97.97, 98.98,
       99.99])

In [5]:
res_arr2 = np.add(arr1, arr2)

In [6]:
res_arr2

array([ 0.  ,  1.01,  2.02,  3.03,  4.04,  5.05,  6.06,  7.07,  8.08,
        9.09, 10.1 , 11.11, 12.12, 13.13, 14.14, 15.15, 16.16, 17.17,
       18.18, 19.19, 20.2 , 21.21, 22.22, 23.23, 24.24, 25.25, 26.26,
       27.27, 28.28, 29.29, 30.3 , 31.31, 32.32, 33.33, 34.34, 35.35,
       36.36, 37.37, 38.38, 39.39, 40.4 , 41.41, 42.42, 43.43, 44.44,
       45.45, 46.46, 47.47, 48.48, 49.49, 50.5 , 51.51, 52.52, 53.53,
       54.54, 55.55, 56.56, 57.57, 58.58, 59.59, 60.6 , 61.61, 62.62,
       63.63, 64.64, 65.65, 66.66, 67.67, 68.68, 69.69, 70.7 , 71.71,
       72.72, 73.73, 74.74, 75.75, 76.76, 77.77, 78.78, 79.79, 80.8 ,
       81.81, 82.82, 83.83, 84.84, 85.85, 86.86, 87.87, 88.88, 89.89,
       90.9 , 91.91, 92.92, 93.93, 94.94, 95.95, 96.96, 97.97, 98.98,
       99.99])

In [20]:
ROWS = int(input("Enter number of rows for matrices: "))

Enter number of rows for matrices: 5


In [21]:
COLS = int(input("Enter number of columns for matrices: "))

Enter number of columns for matrices: 5


In [25]:
m1 = np.reshape(np.tile(arr1[0:COLS:1], ROWS), (ROWS, COLS))
m2 = np.reshape(np.tile(arr2[0:COLS:1], ROWS), (ROWS, COLS))

In [26]:
m1, m2

(array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]),
 array([[0.  , 0.01, 0.02, 0.03, 0.04],
        [0.  , 0.01, 0.02, 0.03, 0.04],
        [0.  , 0.01, 0.02, 0.03, 0.04],
        [0.  , 0.01, 0.02, 0.03, 0.04],
        [0.  , 0.01, 0.02, 0.03, 0.04]]))

In [34]:
res_m = np.zeros((ROWS, COLS))
assert(ROWS == COLS)
for i in range(0, ROWS):
    for j in range(0, COLS):
        for k in range(0, ROWS):
            res_m[i][j] += m1[i][k] * m2[k][j]
res_m

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4]])

In [29]:
res_m1 = m1 @ m2

In [30]:
res_m1

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4]])